version: '3.8'

services:
  # hl_server_go:
  #   container_name: hl_server_go
  #   image: hl_server_go
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - hl_postgres
  #   volumes:
  #     - ./cmd/.env:/home/dev/Projects/hl-server-go/cmd/.env 

  hl_postgres:
    image: postgres:latest
    container_name: hl_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  
volumes:
  db_data:
